Repository jhsung23/pre-onboarding-12th-1-3, pull requests merged in 2023-08, with the labels that each got.

#4 [Feat] Api Config 생성
  src/apis/.gitkeep
  src/apis/auth.ts
  src/apis/axiosInstance.ts
  src/apis/index.ts
  src/apis/todo.ts
Labels: enhancement

#1 [Feat] 페이지 라우팅 설정 및 RootLayout 제작
  src/App.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/common/RootLayout.tsx
  src/components/common/index.ts
  src/index.tsx
  src/pages/HomePage.tsx
  src/pages/index.ts
  src/routes/router.ts
  src/routes/router.tsx
Labels: enhancement

#9 [Fix] Route Merge 오류로 인한 브랜치 변경 재커밋
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/common/RootLayout.tsx
  src/components/common/index.ts
  src/hooks/useAuthForm.tsx
  src/index.tsx
  src/pages/HomePage.tsx
  src/pages/index.ts
  src/routes/router.ts
  src/routes/router.tsx
Labels: bug

#7 [Feat] 투두 CRUD 기능
  src/components/domain/todo/.gitkeep
  src/components/domain/todo/AddTodoForm.tsx
  src/components/domain/todo/TodoItem.tsx
  src/components/domain/todo/TodoList.tsx
  src/components/domain/todo/index.ts
  src/hooks/index.ts
  src/hooks/useDebounceFunc.tsx
  src/hooks/useTodoList.tsx
  src/pages/TodoPage.tsx
Labels: enhancement

#14 [Fix] 페이지 라우팅 리다이렉트 문제 해결
  src/components/common/ProtectedRoute.tsx
  src/routes/router.tsx
Labels: bug

#17 [Docs] README Assignment 4 Best Practice 추가
  README.md
Labels: documentation
